language: csharp
sudo: required
solution: PrisMegahHRSystem.sln
install:
  - nuget restore PrisMegahHRSystem (new)/PrisMegahHRSystem.sln
script:
  - xbuild /p:Configuration=Release PrisMegahHRSystem.sln
